# docker-compose.yml
services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 958606
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"   # host can connect
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  appointment-db:
    image: postgres:15
    container_name: appointment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointment_db
    ports:
      - "5433:5432"   # host connects via localhost:5433
    volumes:
      - appointment_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
  appointment_pgdata:
